BB-272 adds CI test

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -49,15 +49,12 @@ jobs:
     #       POSTGRES_PASSWORD: secretpassword
     env:
       BATON_LOG_LEVEL: debug
-      # Add any environment variables needed to run baton-redis
-      # BATON_BASE_URL: 'http://localhost:8080'
-      # BATON_ACCESS_TOKEN: 'secret_token'
-      # The following parameters are passed to grant/revoke commands
-      # Change these to the correct IDs for your test data
-      CONNECTOR_GRANT: 'grant:entitlement:group:1234:member:user:9876'
-      CONNECTOR_ENTITLEMENT: 'entitlement:group:1234:member'
-      CONNECTOR_PRINCIPAL: 'user:9876'
-      CONNECTOR_PRINCIPAL_TYPE: 'user'
+      BATON_BASE_HOST: 'http://localhost'
+      BATON_API_PORT: '8080'
+      BATON_USER: 'test@redislabs.com'
+      BATON_PASSWORD: 'redislabs123'
+      CONNECTOR_ENTITLEMENT: 'role:1:admin'
+      CONNECTOR_PRINCIPAL: '1'
     steps:
       - name: Install Go
         uses: actions/setup-go@v5
@@ -65,40 +62,59 @@ jobs:
           go-version: 1.22.x
       - name: Checkout code
         uses: actions/checkout@v4
-      # Install any dependencies here (or delete this)
-      # - name: Install postgres client
-      #   run: sudo apt install postgresql-client
-      # Run any fixture setup here (or delete this)
-      # - name: Import sql into postgres
-      #   run: psql -h localhost --user postgres -f environment.sql
-      #   env:
-      #     PGPASSWORD: secretpassword
+
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v2
+
+      # Step 1: Init Redis Enterprise container using HTTP
+      - name: Run Redis Enterprise container
+        run: |
+            docker run -d --cap-add sys_resource --name redis-enterprise \
+            -p 8080:8080 \
+            -e REDIS_ENTERPRISE_API_USE_HTTP=true \
+            redislabs/redis:latest
+
+      - name: Wait for Redis Enterprise container to initialize
+        run: |
+          sleep 30
+
+      - name: Check if Redis Enterprise is running
+        run: |
+          docker ps -a
+
+      - name: Create Redis cluster using rladmin
+        run: |
+            docker exec -d --privileged redis-enterprise "/opt/redislabs/bin/rladmin" cluster create name cluster-ci.local username ${{ env.BATON_USER }} password ${{ env.BATON_PASSWORD }}
+
+      - name: Wait until Redis Enterprise API is ready
+        run: |
+          echo "⏳ Waiting for Redis Enterprise to become healthy..."
+          max_retries=10
+          for i in $(seq 1 $max_retries); do
+            response=$(curl -s -u "${{ env.BATON_USER }}:${{ env.BATON_PASSWORD }}" "${{ env.BATON_BASE_HOST }}:${{ env.BATON_API_PORT }}/v1/nodes" || true)
+            echo "Response: $response"
+            if echo "$response" | grep -q '"status":"active"'; then
+                echo "✅ Redis Enterprise is ready!"
+                break
+            fi
+            echo "⏳ Waiting for Redis Enterprise to become healthy..."
+            sleep 30
+            if [ $i -eq $max_retries ]; then
+              echo "❌ Error: Redis Enterprise is not ready after $max_retries attempts."
+              exit 1
+            fi
+          done
+
       - name: Build baton-redis
         run: go build ./cmd/baton-redis
+
       - name: Run baton-redis
-        run: ./baton-redis
+        run: ./baton-redis --cluster-host ${{ env.BATON_BASE_HOST }} --api-port ${{ env.BATON_API_PORT }} --username ${{ env.BATON_USER }} --password ${{ env.BATON_PASSWORD }}
 
       - name: Install baton
         run: ./scripts/get-baton.sh && mv baton /usr/local/bin
 
-      - name: Check for grant before revoking
+      - name: Check for grants
 
         run:
           baton grants --entitlement="${{ env.CONNECTOR_ENTITLEMENT }}" --output-format=json | jq --exit-status ".grants[].principal.id.resource == \"${{ env.CONNECTOR_PRINCIPAL }}\""
-
-
-      - name: Revoke grants
-        run: ./baton-redis --revoke-grant="${{ env.CONNECTOR_GRANT }}"
-
-      - name: Check grant was revoked
-        run: ./baton-redis && baton grants --entitlement="${{ env.CONNECTOR_ENTITLEMENT }}" --output-format=json | jq --exit-status "if .grants then .grants[]?.principal.id.resource != \"${{ env.CONNECTOR_PRINCIPAL }}\" else . end"
-
-      - name: Grant entitlement
-        # Change the grant arguments to the correct IDs for your test data
-        run: ./baton-redis --grant-entitlement="${{ env.CONNECTOR_ENTITLEMENT }}" --grant-principal="${{ env.CONNECTOR_PRINCIPAL }}" --grant-principal-type="${{ env.CONNECTOR_PRINCIPAL_TYPE }}"
-
-      - name: Check grant was re-granted
-
-        run:
-          baton grants --entitlement="${{ env.CONNECTOR_ENTITLEMENT }}" --output-format=json | jq --exit-status ".grants[].principal.id.resource == \"${{ env.CONNECTOR_PRINCIPAL }}\""
-
